style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/redhat-developer/app-services-operator
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - Docs
        - BREAKING
  commit_groups:
    title_maps:
      BREAKING: BREAKING CHANGES
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      Docs: Documentation  
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE