apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: managedkafkarequests.rhoas.redhat.com
spec:
  group: rhoas.redhat.com
  names:
    kind: ManagedKafkaRequest
    plural: managedkafkarequests
    shortNames:
    - mkr
    singular: managedkafkarequest
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            accessTokenSecretName:
              type: string
            additionalProperties:
              type: object
          type: object
        additionalProperties:
          type: object
        status:
          properties:
            message:
              type: string
            updated:
              type: string          
            lastUpdate:
              type: string
            userKafkas:
              type: object
              additionalProperties: 
                type: object
                properties:
                  id:
                    type: string
                  created:
                    type: string
                  provider:
                    type: string
                  region:
                    type: string
                  owner:
                    type: string
            additionalProperties:
              type: object
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
